version: '3'

services:
  rtsp2mjpg:
    image: norskfjellgeit/rtsp2mjpeg:armhf-latest
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - $PWD/ffserver.conf:/etc/ffserver.conf
    environment:
      RTSP_URL: rtsp://admin:559279@10.0.0.10:554/live/profile.0
#      FFSERVER_LOG_LEVEL: error
#      FFMPEG_LOG_LEVEL: info
#      FFMPEG_INPUT_OPTS: -nostats -use_wallclock_as_timestamps 1 -thread_queue_size 2048 -probesize 25M -analyzeduration 25M -r 15
#      FFMPEG_OUTPUT_OPTS: 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/still.jpg --max-time 1 --output /dev/null || exit 1"]
      interval: 15s
      timeout: 1s
      retries: 3
